options:
  # Resource URLs
  base-api-url:
    type: string
    default:
    description: |
      The cluster-api url.

  # Slurm related settings
  sbatch-path:
    type: string
    default: /usr/bin/sbatch
    description: |
      Absolute path to the sbatch command
  scontrol-path:
    type: string
    default: /usr/bin/scontrol
    description: |
      Absolute path to the scontrol command
  # Auth related settings
  oidc-domain:
    type: string
    default:
    description: |
      OIDC provider domain
  oidc-audience:
    type: string
    default:
    description: |
      OIDC provider audience
  oidc-client-id:
    type: string
    default:
    description: |
      Client ID used to issue JWTs
  oidc-client-secret:
    type: string
    default:
    description: |
      Secret to protect OIDC client resources
  slurm-user-mapper:
    type: string
    default:
    description: |
      Type of user-mapper to use.

  # Other settings
  sentry-dsn:
    type: string
    default:
    description: |
      The client url for sending error events to sentry
  x-slurm-user-name:
    type: string
    default: slurm
    description: |
      The default username to use for requests to the Slurm REST API
  write-submission-files:
    type: boolean
    default: true
    description: |
      Define if the job script files will be written to the submit directory

  # Tasks
  task-jobs-interval-seconds:
    type: int
    default:
    description: |
      Seconds between the job task runs, to submit pending and check running jobs
  task-garbage-collection-hour:
    type: int
    default:
    description: |
      Hour of the day when garbage-collection tasks should be triggered

  # Plugins
  plugins-install:
    type: string
    default:
    description: >
      A string used the install extra plugins on the agent using pip.

      This will be used after `pip install`, so the version and custom arguments
      can be provided as well.

      Example usage:
      $ juju config jobbergate-agent custom-config="agent-plugin==version --index-url 'https://USERPWD@XYZ-DOMAIN.com:443/artifactory/api/pypi/python/simple' --trusted-host=XYZ-DOMAIN.com"
  plugins-config:
    type: string
    default:
    description: >
      User supplied configuration for the plugins installed.

      This will be used as headed of the .env file that configures jobbergate-agent.
      With that, any custom configuration can be provided for the installed plugin.

      Example:
      JOBBERGATE_AGENT_LDAP_URL=<...>
      JOBBERGATE_AGENT_LDAP_CREDENTIALS=<...>
