options:
  # Resource URLs
  base-api-url:
    type: string
    default:
    description: |
      The cluster-api url.
  base-slurmrestd-url:
    type: string
    default: http://127.0.0.1:6820
    description: |
      The url for the Slurm REST API.
  slurm-restd-version:
    type: string
    default: v0.0.36
    description: |
      The target version for the Slurm REST API.

  # Slurmrestd authentication
  slurmrestd-jwt-key-path:
    type: string
    default:
    description: |
      Path to the Slurmrestd JWT secret key
  slurmrestd-jwt-key-string:
    type: string
    default:
    description: |
      Slurmrestd's JWT secret key itself
  slurmrestd-use-key-path:
    type: boolean
    default: true
    description: |
      Whether to use the JWT secret key path or the JWT secret key string

  # Auth related settings
  oidc-domain:
    type: string
    default:
    description: |
      OIDC provider domain
  oidc-audience:
    type: string
    default:
    description: |
      OIDC provider audience
  oidc-client-id:
    type: string
    default:
    description: |
      Client ID used to issue JWTs
  oidc-client-secret:
    type: string
    default:
    description: |
      Secret to protect OIDC client resources
  slurm-user-mapper:
    type: string
    default:
    description: |
      Type of user-mapper to use.

  # Other settings
  sentry-dsn:
    type: string
    default:
    description: |
      The client url for sending error events to sentry
  x-slurm-user-name:
    type: string
    default: slurm
    description: |
      The default username to use for requests to the Slurm REST API

  # Tasks
  task-jobs-interval-seconds:
    type: int
    default:
    description:
      Seconds between the job task runs, to submit pending and check running jobs
  task-garbage-collection-hour:
    type: int
    default:
    description:
      Hour of the day when garbage-collection tasks should be triggered

  # Plugins
  plugins-install:
    type: string
    default:
    description: >
      A string used the install extra plugins on the agent using pip.

      This will be used after `pip install`, so the version and custom arguments
      can be provided as well.

      Example usage:
      $ juju config jobbergate-agent custom-config="agent-plugin==version --index-url 'https://USERPWD@XYZ-DOMAIN.com:443/artifactory/api/pypi/python/simple' --trusted-host=XYZ-DOMAIN.com"
  plugins-config:
    type: string
    default:
    description: >
      User supplied configuration for the plugins installed.

      This will be used as headed of the .env file that configures jobbergate-agent.
      With that, any custom configuration can be provided for the installed plugin.

      Example:
      JOBBERGATE_AGENT_LDAP_URL=<...>
      JOBBERGATE_AGENT_LDAP_CREDENTIALS=<...>
